runtime: go112

inbound_services:
  - warmup

handlers:
  - url: /_dev/console/
    static_files: static/swagger-ui/index.html
    upload: static/swagger-ui/index.html

  - url: /_dev/console/(.*)
    static_files: static/swagger-ui/\1
    upload: static/swagger-ui/(.*)

  - url: /_admin/dashboard/
    static_files: static/viron/index.html
    upload: static/viron/index.html

  - url: /_admin/dashboard/(.*)
    static_files: static/viron/\1
    upload: static/viron/(.*)

  - url: /.*
    script: auto
